DataDog/datadog-go

statsd/statsd.go
statsd/statsd_test.go

A small PR bringing the great work from @sschepens in #7. Because we had taken a long time to review his PR I decided to just consolidate it here a little bit, and rewrite one of the functions and test in an effort to make the code a little more readable.

Split messages in maximum UDP message size when buffering - Refactor

---

statsd/statsd.go
statsd/statsd_test.go

This change makes some enhancements to the `Client.sendMsg()` method.
Specifically the following changes have been made:
* check the length of the message, whether buffered or unbuffered, and
return an error if it's too long
* take the `sync.Mutex` lock inside of the `Client.append()` method,
where it's needed, instead of in `Client.sendMsg()`
In addition to the changes above, the unit tests of this method have
been enabled / refactored to actually work.
Fixes #24
Signed-off-by: Tim Heckman <t@heckman.io>

Client.sendMsg(): check payload len for all messages; add tests

---

statsd/statsd.go

(decr is a count of -1 not 1)
Small documentation change.

Update decr documentation to match implementation

---

statsd/statsd.go
statsd/statsd_test.go

Adding a new Distribution type to track accurate percentile sketches.

Add distribution type for percentile sketches

---

statsd/statsd.go
statsd/uds.go

https://goreportcard.com/report/github.com/DataDog/datadog-go

Fixing Golint Issues as reported by goreportcard.com

---

statsd/statsd.go
statsd/statsd_test.go

We're using datadog to have metrics of panics, but sometimes nobody recovers those panics and as we're using a buffered client, we lose those events/metrics. 
This is slightly different from #18 as we don't want to close the client, maybe someone on the stack knows how to recover that panic, but we do want to make sure our event was sent, so the usage for this would be like:
```go
if err := recover(); err != nil {
client.Event(...)
client.Flush()
panic(err)
}
```

Exported Flush() function of the client

---

statsd/statsd.go
statsd/statsd_test.go

Flush the buffer on Close()

---

statsd/statsd_test.go
statsd/uds.go

Each commit message has more info.
I added a failing test that highlighted the issue first before adding the code to fix it.
The CI already runs with the race detector enabled so it should be able to test the change properly.

UDS: make writer able to deal with concurrent writes

---

statsd/uds.go
statsd/uds_blocking.go

This PR rebases #74 and includes the original changes submitted by @KJTsanaktsidis, it's merely a rebase after the introduction of the async non-blocking writer with #81
Thank you for your contribution @KJTsanaktsidis

uds: chage Mutex to RWMutex for fast already-connected path (rebase)

---

README.md

Adds some insight about the various parameters used to send a metric to the documentation.
#70
#69

usage docs improvements

---

CHANGELOG.md

Currently targeting arbll/perf-overhaull till #91 is merged

3.0.0 changelog

---

.github/CODEOWNERS
README.md

This PR updates the main readme.md file in order to properly reflect the main functionalities of this DogStatsD lib.
It also adds Datadog documentation team as a code owner over Markdown files in order to smooth further doc improvement + insuring better sync between public doc and the functionalities of Datadog-go

Doc update

---

README.md
statsd/options.go
statsd/options_test.go
statsd/statsd.go

Fixes https://github.com/DataDog/datadog-go/issues/114

add an option to disable telemetry, document available metrics

---

CHANGELOG.md
README.md
statsd/statsd.go

Updating telemetry tags and documentation.

Updating telemetry tags and documentation

---

CHANGELOG.md
statsd/statsd.go

Release of 3.4.1

---

statsd/sender.go
statsd/statsd.go
statsd/statsd_test.go

Adding basic test on the telemetry

Adding basic test on the telemetry

---

statsd/options.go

Fix option typo for aggregation interval

Fix option typo for aggregation interval

---

statsd/aggregator.go
statsd/statsd.go
statsd/telemetry.go
statsd/telemetry_test.go

Adding telemetry on the number of aggregated contexts

Adding telemetry on the number of aggregated contexts

---

README.md

In order to help with special scenarios where this value should be adjusted.

[README] add a section on the maximum packets size knob

---

CHANGELOG.md
statsd/telemetry.go

Releasing 4.2.0

---

statsd/telemetry.go
statsd/telemetry_test.go

This makes the telemetry for the beta client aggregation easier to graph and use

Update devMode telemetry naming and taging

---

CHANGELOG.md
statsd/telemetry.go

Releasing 4.6.0

---

CHANGELOG.md
statsd/telemetry.go

Releasing 4.8.1

---

statsd/aggregator.go
statsd/buffered_metric_context.go

New metrics could overwrite each other when sampled for the first time.

Fix race condition in aggregation

---

CHANGELOG.md
statsd/end_to_end_udp_test.go
statsd/options.go
statsd/options_test.go
statsd/telemetry_test.go
statsd/test_helpers_test.go

Client side aggregation is no longer in BETA.

Enable basic client side aggregation by default.

---

CHANGELOG.md

Tiny changes to the v5 changelog

[changelog] Small rewording

---

example/simple_example.go
go.mod
go.sum
statsd/statsd.go
statsd/uds.go
statsd/uds_test.go
statsd/uds_windows.go

This is an experimental transport that will allow to have one connection.

Add support for AF_UNIX+SOCK_STREAM

---

CHANGELOG.md

Updates the changelog with the new origin detection features for version 5.7.0.

Release 5.7.0
