DataDog/datadog-go

.travis.yml
Problems with go compile 1.5, test have timeout.
Version 1.4 works fine.
https://travis-ci.org/abtris/datadog-go
=> Add travisci integration

statsd/statsd.go, statsd/statsd_test.go
Tests were failing when using go 1.5. Datagrams were never processed by the server. The only real change is the usage of `net.DialUDP` instead of `net.Dial`.
=> Fix UDP Dial for go 1.5

statsd/statsd.go
The [docs](http://docs.datadoghq.com/guides/dogstatsd/#events) state that dogstatsd events support line breaks. However, using the Go-Library to submit events, I discovered, that just the first line of the event text was delivered successfully.
Apparently, the [dogstatsd agent unescapes](https://github.com/DataDog/dd-agent/blob/master/aggregator.py#L500-L501) newline chars. and the [python client escapes them](https://github.com/DataDog/datadogpy/blob/b5f7d6d2748fad61b2e060768ce68e3b76d2c928/datadog/dogstatsd/base.py#L259-L260). Therefore, I suggest that the go client library should do the same.
=> Escape newline chars in event texts

statsd/statsd.go
https://github.com/DataDog/datadog-go/pull/8 breaks the datadog-go:
```bash
$ go get -u
../../DataDog/datadog-go/statsd/statsd.go:358: e.text undefined (type Event has no field or method text, but does have Text)
```
Fixing to properly reference the Event Text attribute.
=> Fixing typo introduced in 694a2805f0014581c9da2bfbe2acd3192517eac7

statsd/statsd.go
Simplified example of how this bug works: https://play.golang.org/p/yIxB5LPORx
Detailed repro scenario:
1. suppose `c.Tags` has capacity > length (this is quite possible since it's provided by the caller, eg the example at the top of the file `c.Tags = append(c.Tags, "us-east-1a")` would probably result in capacity>length)
2. caller 1 enters the `format` function, passing in a single tag. It reaches line 117 and executes `append`
3. since `c.Tags` has residual capacity, the underlying memory of the `c.Tags` slice is mutated so that the next element contains caller 1's tag. Caller 1's `format` invocation receives a slice pointing to the underlying memory of `c.Tags`, but with length of `len(c.Tags) + 1`.
4. before caller 1 can continue any further, caller 2 enters the `format` function, …
=> Do not append to shared slice

statsd/README.md, statsd/statsd.go, statsd/statsd_test.go
Adds additional convenience methods `Incr`, `Decr` and an alias for `Timing` for `TimeInMilliseconds`. It also adds additional documentation for new and old functions.
Other Datadog clients (and StatsD in general) include an increment and decrement method for convenience. Perhaps I'm lazy. :)
The `TimeInMilliseconds` method feels prescriptive to me, especially since:
* From what I understand, golang — which I'm admittedly new to — tends to work in nanoseconds. [Duration](https://golang.org/pkg/time/#Duration) doesn't have a `Milliseconds()`, so it feels odd to pass nanoseconds to such a clearly named method.
* Datadog's timer support does not imply any specific unit. The percentiles and such that come out of a timer lack metadata and do not have a unit of `milliseconds` at all.
This is a …
=> Add Incr, Decr, Timing and more docs.

statsd/statsd.go, statsd/statsd_test.go
If someone puts a newline in a tag, the content after the newline will be parsed as a completely new statsd message (because newlines are considered to be a message separator in the protocol). One way or another we have to get rid of them. Since newline escapes are not supported in tags, we simply remove them altogether.
cc @ChimeraCoder @krisreeves-stripe
=> Remove newlines from tags

statsd/statsd.go, statsd/statsd_test.go
Currently it is not possible to build a full interface for statsd.Client due to serviceCheckStatus being unexported. Example:
```
type StatsdClient interface {
...
SimpleServiceCheck(name string, status byte) error
...
}
```
Does not match the status.Client.SimpleServiceCheck signature. Exporting the type allows for the following:
```
type StatsdClient interface {
...
SimpleServiceCheck(name string, status statsd.ServiceCheckStatus) error
...
}
```
Which fulfills the interface.
If you know of a different way to get this to work without changing the type please let me know.
=> Export serviceCheckStatus so interfaces can be built for statsd.Client

statsd/statsd.go, statsd/statsd_test.go
We have code in place to check for `Client == nil` for Gauge, Count, etc., and when Client is `nil` nothing is sent. For Events, this is not the case; it currently panics with a `nil` Client. Let's fix that!
=> Do not panic on Client.Event when nil

statsd/statsd.go, statsd/statsd_benchmark_test.go, statsd/statsd_test.go
Resubmission of [PR23](https://github.com/DataDog/datadog-go/pull/23)
The results of running the benchmark
```
BenchmarkFormatV1-8   	10000000	      3057 ns/op
BenchmarkFormatV2-8   	20000000	      1769 ns/op
BenchmarkFormatV3-8   	20000000	      1392 ns/op
```
=> Improve message building speed by using less fmt.Sprintf

statsd/statsd.go, statsd/statsd_test.go
Reverts DataDog/datadog-go#34 since we don't want to make this public yet.
=> Revert "Add distribution type for percentile sketches"

statsd/README.md, statsd/statsd.go, statsd/statsd_test.go, statsd/udp.go, statsd/uds.go
Add Unix Domain Socket support, as implemented in DSD6.
Protocol and error handling follows the specs at https://github.com/DataDog/datadog-agent/wiki/Unix-Domain-Sockets-support
Documentation will be updated once code is OK.
=> Add UDS support

statsd/statsd.go
I am "code complete" but wanted to give some more information on:
I don't think the code will change though... 
So, while I'm adding these 2 things, any questions/concerns on the code change?
@masci 
(cc. @dm03514)
=> Exporting eventAlertType and eventPriority types

statsd/statsd_test.go, statsd/uds.go
Under some circumstances, for example when an uds client has not written any data yet, the uds connection can be nil. In such cases when applications try to close statsd client it panics.
=> Preventing the (*udsWriter).Close method from panic 

statsd/statsd.go, statsd/statsd_test.go
We want to persist metrics to a storage while/before sending it to datadog agent.
=> client: add new constructor, accepting a connection

.travis.yml, statsd/statsd.go, statsd/statsd_test.go, statsd/udp.go, statsd/uds.go
* As PR title, `statsdWriter` now implements `io.Writer`.
* Removed a dependency from kernel settings that made tests fail on different platforms
* For the same reasons, removed some error type checking from the UDS client that was broken on mac
* Added 1.9 and removed 1.4 from the test matrix
=> Make statsdWriter implement io.Writer

statsd/statsd.go, statsd/statsd_test.go
This addresses https://github.com/DataDog/datadog-go/issues/51 . It turns all remaining public `statsd.Client` methods into no-ops if the client is nil:
- `SetWriteTimeout`
- `Flush`
- `ServiceCheck`
- `SimpleServiceCheck`
I also added a nil test on `Event` to make sure it's covered, just in case `SimpleEvent` doesn't use Event in the future.
=> Protect remaining client methods from nil client

statsd/statsd.go, statsd/statsd_benchmark_test.go, statsd/statsd_test.go
Hello, I was reviewing this library as I may start using it at work. I noticed that there are some opportunities for reducing allocations. This can be taken farther, but I figured I'd open the conversation by working on `Client.format`.
The stack allocated buffer is 200 bytes simply because I figured it would be plenty large. The size can be adjusted if someone has a more educated guess at a reasonable upper bound of the message size.
Thanks!
Summary:
* Avoid conversions to/from `string` as much as possible.
* Preallocate a sufficiently large `[]byte` in `Client.format` and use it in such a way that it doesn't escape. This allows the compiler to stack allocate the buffer.
* Copied test cases from existing tests to use in benchmark.
Results (`go version go1.10 darwin/amd64`):
```
name …
```
=> Reduce `Client.format` allocations

README.md, statsd/statsd.go, statsd/statsd_test.go, statsd/udp.go, statsd/udp_test.go
In order to ease dogstatsd usage in containerized environments, we are implementing standard environment variables common to all client libraries (both dogstatsd and trace). This PR is the first implementation for dsd.
Introduce support of the `DD_AGENT_HOST` and `DD_DOGSTATSD_PORT` environment variables, that can be set via the orchestrator on the applicative container. Logic is as following:
- explicit configuration (`addr` param) always take over. If it's empty, run the autoconfiguration logic
- `DD_AGENT_HOST` is required, configuration fails if it's not set
- `DD_DOGSTATSD_PORT` is optionnal, library defaults to the default `8125` port if not set
Support the `DD_ENTITY_ID` envvar, injected by the orchestrator in the applicative container. If found, it is added as a constant …
=> Support configuring the client from standard environment variables

README.md, statsd/README.md, statsd/options.go, statsd/options_test.go, statsd/statsd.go, statsd/uds.go, statsd/uds_async.go, statsd/uds_blocking_test.go, statsd/uds_test.go
This PR adds a generic way to deal with the client configuration. I decided to use function options here for the implementation. This is discussable and definitely has it's pro and cons. However I prefer it over it's alternative, using a configuration struct, since it allows for dumb default value logic while using a struct would add quite a bit of complexity dealing with Golang zero values. I'm happy to discuss if someone has an opinion here.
The list of options is growing and some new ones require to be known at the client creation. Creating new constructors like `NewBuffered` is not scalable. 
Allowing options to be mutable after the client creation isn't a very good practice IMO.
=> configuration at client creation

statsd/noop.go, statsd/noop_test.go, statsd/statsd.go
Can be useful for testing and mocking for downstream library users.
Resolves #88
=> Add a NoOp client

statsd/format.go, statsd/statsd.go
- After checking the go report, I found a misspelling and corrected it.
- https://goreportcard.com/report/github.com/DataDog/datadog-go
=> Fixed typo

statsd/noop.go, statsd/noop_test.go, statsd/statsd.go
Address https://github.com/DataDog/datadog-go/pull/92#issuecomment-546185482
Currently we cannot build the following code:
```go
package main
import (
"os"
"github.com/DataDog/datadog-go/statsd"
)
func main() {
var c statsd.ClientInterface
if addr := os.Getenv("DATADOG_STATSD_ADDR"); addr != "" {
var err error
c, err = statsd.New(addr)
if err != nil {
panic(err)
}
} else {
c = &statsd.NoOpClient{}
}
defer c.Close()
c.Incr("foo", nil, 1)
}
```
```
❯ go build main.go
./main.go:20:9: c.Close undefined (type statsd.ClientInterface has no field or method Close)
``` 
I think this should work.
This PR lets NoOpClient implement all public methods of Client so that the above code works.
=> Let NoOpClient implement all public methods of Client

statsd/sender.go, statsd/statsd.go, statsd/statsd_test.go
This patch fixes a resource leak that occurs when closing a statsd client.
The Close function sent an empty struct to the stop channel, but there were two
goroutines waiting on the stop channel. Since the Close function did not close
the stop channel, one of the two goroutines would not exit, and would instead be
leaked along with any memory resources the statsd client held.
This patch causes the Close function to close the stop channel, ensuring any
goroutines listening on that channel will know the client has been stopped.
=> statsd: close the stop channel when closing a statsd client to avoid leaking.

statsd/statsd.go
Fixes the unix socket path extraction logic. 
`unix:///path` would be extracted as `//path` instead of `/path`.
Fixes https://github.com/DataDog/datadog-go/issues/104
This bug should have no effect on *nix as any number of consecutive `/` get collapsed into one.
It was present since the beginning of UDS support. https://github.com/DataDog/datadog-go/blob/9e6cdfed49057db82734fd6d137372972a36f3eb/statsd/statsd.go#L108
=> fix unix socket path extraction

statsd/uds.go, statsd/uds_test.go
A `nil` error check was missing in `udsWriter.Write` leading to unneeded re-connections. 
This added significant overhead to the `Write` method.
=> fix uds.Write error check leading to unneeded re-connection

statsd/statsd_test.go
The race only happen when also runnin the benchmark which leave enough time to the un-closed client to flush
=> Fix race condition in the test

statsd/statsd.go
Cherry-pick of #124 without the test. It's not possible to reproduce the deadlock without complexifying the code. This PR cherry-pick the fix without the test.
=> Fix potential deadlock on Close()

README.md, statsd/client_test.go, statsd/statsd.go
This PR adds support for:
- `DD_ENV`
- `DD_SERVICE`
- `DD_VERSION`
to be used by the statsd client at initialization. The first three are added as global tags for `{env, service, version}`, if they are set.
=> Add support for DD_ENV, DD_SERVICE, and DD_VERSION environment variables

statsd/client_test.go, statsd/fnv1a.go, statsd/options.go, statsd/options_test.go, statsd/statsd.go, statsd/statsd_benchmark_test.go, statsd/worker.go
We had a single buffer we wrote all serialized metrics to. It was creating contention when multiple Goroutines where pushing metrics at the same time. This PR tries to address this issue by instead using a configurable number of buffers to reduce the chance two Goroutines write to the same buffer at the same time.
To implement this, we need a way to decide to which buffer we should write when a metric is submitted.
Currently, this PR uses the metric name to do so:
https://github.com/DataDog/datadog-go/blob/12805b4c7a2528b930591bd6d14fea0e031d6aa2/statsd/statsd.go#L389-L390
Using `bench.RunParallel`. Each goroutine sends metrics with a different name:
```
benchmark                      old ns/op     new ns/op     delta
BenchmarkStatsdUDP-4          219           105           -52.05% …
```
=> shard buffers to reduce lock contention

statsd/benchmark_report_metric_noop_test.go, statsd/benchmark_report_metric_test.go, statsd/options.go, statsd/statsd.go, statsd/statsd_benchmark_test.go, statsd/statsd_test.go, statsd/worker.go
This PR add a "drop mode" to the DogStatsD client.
The current implementation uses mutexes sharded by metric name. This is the
fastest way to accept metrics but can create lock contention when sending a
very high number of metrics per second from multiple goroutine.
The mutex sharding solve the use case of multiple goroutine sending different
metrics or just sending a normal number of points per second (in the hundreds of
thousand per second).
But, at a very high rate (millions of points per second or above), the
application will be slowed down by dogstatsd due to lock contention. The new
"drop mode" based on channel is slower than mutexes but will actually drop
metrics when the channel is fulled. This is a trade off between never slowing
down the application but drop point.
The new "drop …
=> Adding a drop mode to the client

statsd/uds_test.go
This fixes a dropped `err` variable in the tests for the `statsd` package.
=> statsd: fix dropped test error

statsd/sender.go, statsd/statsd_test.go
We need to first stop the receiving loop before flushing data to the transport.
=> Fix close logic in the sender

statsd/statsd.go, statsd/statsd_test.go
This allows libraries to add options to the main dogstatsd client
without impacting the main application.
=> Adding a clone method to the client

statsd/options.go, statsd/options_test.go
We are using DogStatsD client in Python and Go. In the Python client,  `.` is automatically appended to the given namespace. 
https://github.com/DataDog/datadogpy/blob/v0.35.0/datadog/dogstatsd/base.py#L338
But the Go client doesn't, which is a bit confusing for me. 
As far as I checked, most of clients seem to have the same behavior.
- [C#](https://github.com/DataDog/dogstatsd-csharp-client/blob/4.0.1/src/StatsdClient/DogStatsdService.cs#L183)
- [Java](https://github.com/DataDog/java-dogstatsd-client/blob/v2.9.0/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java#L615)
- [Ruby](https://github.com/DataDog/dogstatsd-ruby/blob/v4.8.0/lib/datadog/statsd.rb#L91)
- [PHP](https://github.com/DataDog/php-datadogstatsd) seems not to have the prefix feature 
So I'd like the Go client to …
=> Automatically append dot to namespace

statsd/statsd.go, statsd/statsd_test.go
it seems like an obvious oversight that this wasn't done already... its basically impossible to track these metrics against where they come from without applying some sort of tags to identify the origin.
=> report telemetry tags with the same set as global tags

statsd/client_test.go, statsd/statsd.go
Fix CloneWithExtraOptions panic when given a nil client
=> Fix CloneWithExtraOptions panic when given a nil client

.travis.yml, statsd/sender.go, statsd/statsd.go
Fix panic on atomic operation on non 64bit align variables.
We now also run tests on 32bit and ARM.
This will fix #142.
=> Fix panic on atomic operation on non 64bit align variables

CHANGELOG.md, statsd/options.go, statsd/options_test.go, statsd/statsd.go, statsd/statsd_test.go, statsd/telemetry.go, statsd/telemetry_test.go
New option `WithTelemetryAddr` support UDP  and UDS like the rest of the client.
=> Adding the option to send telemetry to another endpoint

statsd/client_test.go
This picks up an `err` variable that was being dropped in `TestDDEnvServiceVersionTagsEmitted()`.
=> Fix Dropped Test Error

.travis.yml, README.md, example/simple_example.go, statsd/telemetry.go, statsd/telemetry_test.go
Namespace issue was brought back when splitting it from the main client
to allow sending metrics to a different endpoint.
=> Fix telemetry namespace

.travis.yml, README.md, example/simple_example.go
Drop support for EOL Go version 1.8 to 1.11.
=> Drop support for EOL Go version 1.8 to 1.11

statsd/sender.go, statsd/statsd.go, statsd/worker.go
In some case, the sender 'sendLoop' would pop a buffer from its queue
as we are calling its 'flush' method. Since the input queue is empty it
would return instantly without waiting for the current buffer own by the
sender to be sent. This would result in partial flush.
We now synchronize 'flush' and 'sendLoop' to make sure flushing the
client will send everything to the wire. The side effect of this is that
the workers are lock for longer as we keep them locked when flushing the
sender.
=> Fix incomplete flush in the sender when flushing the client

statsd/aggregator.go, statsd/options.go, statsd/options_test.go, statsd/statsd.go, statsd/statsd_test.go, statsd/telemetry.go, statsd/telemetry_test.go
Adding a `DevMode` to the client.
The new mode will send more telemetry metrics allowing users to more easily troubleshoot issues and usage of the client.
Also,  this makes the telemetry creator functions private. Those function should not have been public in the first place and there signature should not be part of the public API we support. Users shouldn't have any reason to use them as they can control everything through the client options.
=> Adding a DevMode to the client

statsd/aggregator.go, statsd/aggregator_test.go, statsd/metrics.go, statsd/metrics_test.go, statsd/statsd.go
Mixing sampling rate and aggregation doesn't make sens and could be erroneous if users sends the same metrics with different sampling rate.
=> Drop sampling rate when aggregation is enabled

statsd/statsd.go, statsd/statsd_benchmark_test.go
Use better defaults for UDS. This means setting the UDS defaults to:
* 8KB datagrams
* change internal buffer and queue sizes accordingly to avoid
increasing the mem usage of the client
Follow-up to https://github.com/DataDog/datadog-go/pull/91, which left the UDS defaults similar to the UDP ones because of Agent-side performance limitations that were subsequently fixed in https://github.com/DataDog/datadog-agent/pull/4573 (7.17.0/6.17.0).
=> [UDS] Use better payload size defaults

statsd/worker.go, statsd/worker_test.go
Use a separate random number source per worker. Currently, the `worker` function `shouldSample()` calls `rand.Float64()`, which uses a lock to serialize all calls to the package-global pseudorandom number generator, creating lock contention between all instances of `worker`.
Changes:
- Create and seed a separate pseudorandom number generator for every `worker` to remove the lock contention https://github.com/DataDog/datadog-go/issues/80
- Add a test for the `shouldSample()` function to assert that it returns `true` the expected percentage of the time
- Add a benchmark for the `shouldSample()` function to measure improvement from removing lock contention
```
name            old time/op  new time/op  delta
ShouldSample     444ns ± 0%   190ns ± 1%  -57.26%  (p=0.000 n=8+9)
ShouldSample-2 …
```
=> Use a worker-specific random source to remove lock contention.

statsd/aggregator.go, statsd/aggregator_test.go, statsd/buffer.go, statsd/buffer_test.go, statsd/format.go, statsd/format_test.go, statsd/metrics.go, statsd/metrics_test.go, statsd/options.go, statsd/options_test.go, statsd/statsd.go, statsd/telemetry.go, statsd/telemetry_test.go, statsd/worker.go, statsd/worker_test.go
full client side aggregation for histogram and distribution. This feature use the new beta protocol 1.1 for dogstatsd allowing sending multiple values per message.
This also add the `WithAgentMinVersion` setting to trigger feature link to the agent version. For now only client side aggregation for histograms, distribution and timing which requires agent `>=7.25` or `>=6.25&&<7.0.0`.
=> [BETA] Full client-side aggregate with histogram, distribution and timing

statsd/worker.go
`rand.NewSource` is not thread safe. Each worker needs its own random and random-lock.
=> Fix worker random race condition

statsd/buffer.go, statsd/worker.go, statsd/worker_test.go
Fix multi-metric aggregation in one message
=> Fix multi-metric aggregation

statsd/pipe.go, statsd/pipe_windows.go, statsd/pipe_windows_test.go, statsd/statsd.go
This change adds support for Windows Named Pipes. They may be used when
this option is [enabled in the Datadog Agent](https://github.com/DataDog/datadog-agent/pull/6830).
=> statsd: add support for Windows Pipes

statsd/pipe_windows.go, statsd/pipe_windows_test.go
This changes ensures that the Windows Pipe statsdWriter attempts
reconnecting after losing a connection.
=> statsd: ensure Windows Pipe writer tries to reconnect when losing connection

statsd/statsd_test.go
Adds a `statsd.Client` test that can detect data races when recording metrics from separate goroutines.
Inspired by the bug introduced in https://github.com/DataDog/datadog-go/pull/178 and fixed with https://github.com/DataDog/datadog-go/commit/5cfbb1464e67fe05d7a6ba65c1a4c7dbe06b8420.
=> Add a Client test that can detect data races when emitting metrics from separate goroutines.

statsd/options.go, statsd/uds.go
Increase default UDS timeout from 1ms to 100ms. This will help better handle spike in the number of metrics sent by the client as well as align the Go dogstatsd client with C# and Java.
=> Increase default UDS timeout from 1ms to 100ms

statsd/pipe_windows.go
This allows the client creation call (`New`) with a windows named pipe
target address to be successful even if the Agent hasn't created the
named pipe yet.
This new behavior is consistent with the UDS writer.
I haven't tested the change on Windows, relying on CI to catch any regression on Windows.
=> [win pipes] Defer connection establishment to first write

statsd/aggregator.go, statsd/aggregator_test.go, statsd/buffered_metric_context.go, statsd/options.go, statsd/statsd.go, statsd/statsd_test.go, statsd/telemetry_test.go, statsd/utils.go, statsd/worker.go, statsd/worker_test.go
When using extended aggregation we still want to respect sampling rate for histograms, distribution and timing as it will have direct consequences on the Agent (number of metrics to aggregate).
For app sending a very high number of metrics the aggregator implements ChannelMode to avoid lock contention when generating 
andom numbers.
=> Implement ChannelMode and sampling rate for extended aggregation

statsd/statsd.go, statsd/statsd_test.go
When extended aggregation is enabled with channelMode we don't need to
run the workers in channelMode since the user never use them directly
(the aggregator sit in between). The telemetry on the other side was
using the workers in channelMode despite them not being reading on the
end of the channel. This caused the telemetry to never been sent.
=> Fix telemetry with extended aggregation and channelMode

statsd/options.go
When sending a count metric that increments at a constant 1000/sec,
client-side aggregation causes it to appear noisy, reporting values
of 900, 900, 1200 instead of the constant 1000/sec. This appears to
be mostly caused by mismatched reporting intervals. The client-side
aggregation is reporting every 3 seconds, while the agent is
reporting every 10 seconds. This means in each agent bucket, the
values are: 9000, 9000, 12000, ... . Setting the flush interval to
2 seconds corrects this issue.
=> DefaultAggregationFlushInterval: 3s -> 2s; reduce sampling aliasing

statsd/buffer.go, statsd/buffer_test.go, statsd/statsd_test.go, statsd/worker.go
Now the same precision is used all the time.
=> Fix differentce in precision for timing when extended aggregation is enabled or not

statsd/statsd.go, statsd/telemetry_test.go, statsd/test_helpers_test.go
The telemetry metrics should not use the user namespace.
Before this PR: the metric namespace would still be added to telemetry metrics when telemetry is not configured with its own endpoint.
This commit also include a rework in the tests that allows us to test the telemetry from start to finish (end-to-end)
=> Fix telemetry using the global namespace

CHANGELOG.md, statsd/options.go, statsd/options_test.go, statsd/statsd.go, statsd/statsd_test.go, statsd/telemetry.go, statsd/telemetry_test.go, statsd/test_helpers_test.go
The telemetry behind DevMode are now part of the telemetry by default.
They prove to be very useful and don't have a significant impact on
performance.
=> [V5] Remove DevMode

CHANGELOG.md, statsd/client_test.go, statsd/noop.go, statsd/noop_test.go, statsd/options.go, statsd/options_test.go, statsd/pipe.go, statsd/pipe_windows.go, statsd/sender.go, statsd/sender_test.go, statsd/statsd.go, statsd/statsd_test.go, statsd/telemetry.go, statsd/udp.go, statsd/uds.go, statsd/uds_test.go
WithWriteTimeoutUDS has been removed in favor of WithWriteTimeout (since we now have UDS and named pipe that support write timeout).
=> Removing 'SetWriteTimeout' method in favor of WithWriteTimeout

CHANGELOG.md, statsd/statsd.go, statsd/statsd_benchmark_test.go, statsd/telemetry.go
Those const are now private:
- WriterNameUDP
- WriterNameUDS
- WriterWindowsPipe
- TelemetryInterval
=> Removing private field from the public interface

CHANGELOG.md, statsd/client_test.go, statsd/statsd.go, statsd/statsd_test.go, statsd/telemetry.go, statsd/uds_test.go
Both attribute were not thread safe. 'WithNamespace' and WithTags'
options should be used instead.
=> Remove 'Namespace' and 'Tags' from the public API.

CHANGELOG.md, statsd/aggregator.go, statsd/options.go, statsd/options_test.go, statsd/pipe.go, statsd/sender.go, statsd/statsd.go, statsd/statsd_test.go, statsd/test_helpers_test.go, statsd/uds_windows.go
Only the part needed by the client app are left in the public API. This
also improve/clarify the Options documentation.
=> Move Options internals outside of the public API

CHANGELOG.md, statsd/client_test.go, statsd/statsd.go
Instead of 'statsd.NewBuffered(add, bufferLength)' please use 'statsd.New(addr, statsd.WithMaxMessagesPerPayload(bufferLength))'
=> Removing method 'NewBuffered'

CHANGELOG.md, statsd/client_test.go, statsd/statsd.go
`SkipErrors` was never used anywhere
=> Removing unused field 'SkipErrors'

CHANGELOG.md, statsd/aggregator.go, statsd/buffer.go, statsd/buffer_test.go, statsd/event.go, statsd/event_test.go, statsd/format.go, statsd/format_benchmark_test.go, statsd/format_test.go, statsd/options.go, statsd/options_test.go, statsd/pipe.go, statsd/sender.go, statsd/service_check.go, statsd/service_check_test.go, statsd/statsd.go, statsd/statsd_test.go, statsd/test_helpers_test.go, statsd/uds_windows.go, statsd/worker.go
This remove the unused method Encode and makes the Event and
ServiceCheck methods use a pointer as returned by the 'NewEvent' and
'NewServiceCheck' method. This is more consistant with the rest of the
code base.
=> Removing useless Encode method for event and service_check

CHANGELOG.md, statsd/aggregator.go, statsd/buffered_metric_context.go, statsd/sender.go, statsd/statsd.go, statsd/statsd_benchmark_test.go, statsd/statsd_test.go, statsd/telemetry.go, statsd/telemetry_test.go, statsd/test_helpers_test.go
This allows client app to dynamically adapt its behavior (sampling rate, metrics
submission patterns, number of metric sent ...) based on packet drop for
example.
Metrics are now forever increasing making it resilient to packet drop. This means they are not sent as gauge.
=> Add the method 'GetTelemetry' to retrieve the internal telemetry

README.md, example/simple_example.go, go.mod, go.sum, statsd/statsd_benchmark_test.go
Currently we cant use v5 via go mod. We need to define v5 at go.mod
=> Fix go mod for v5 release

statsd/pipe_windows_test.go, statsd/uds_windows.go
Currently, version v5 of the library cannot be used on **Windows**, let's try
```
go test ./statsd
```
ends
```
statsd\statsd.go:264:25: too many arguments in call to newUDSWriter
have (string, time.Duration)
want (string)
statsd\uds_windows.go:8:33: undefined: io
FAIL    github.com/DataDog/datadog-go/v5/statsd [build failed]
FAIL
```
This PR fixes it, by
- adding missing `import io` (change has been already proposed by https://github.com/DataDog/datadog-go/pull/241, thanks @evanj)
- updating arguments expected by `newUDSWriter` for **Windows**
- increasing timeouts (I run it on flaky **Windows** VM with limited resources and original timeouts weren't sufficient, I've seen similar fix https://github.com/DataDog/datadog-go/pull/239)
In the future could you add CI testing on **Windows** …
=> Fix Windows compatibility for v5

.circleci/config.yml, .github/workflows/datadog-go.yaml
Github actions offer better windows support for Golang than circleCI. And they're overall simpler to use. We keep circleCI for ARM64-linux.
=> Use github actions to run tests for linux and windows amd64

.github/workflows/codeql-analysis.yml
Static code analysis on `datadog-go` using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code. As the repository is small, no security alerts were found during the scan.
=> Setting up codescanning for  datadog-go

statsd/buffer.go, statsd/options.go, statsd/statsd_test.go
This allows users to check the error type when sending message that can't fit in a buffer.
Resolve #251
=> Export internal error as `MessageTooLong`

statsd/noop.go, statsd/statsd.go, statsd/statsd_test.go
fix issues https://github.com/DataDog/datadog-go/issues/140
=> feat: add IsClosed method statsd client

statsd/aggregator.go
This is a bugfix PR that prevents the aggregator's ticker from being leaked when the statsd client is closed.
For reasons that aren't super interesting, we have an app that periodically allocates and closes statsd clients, e.g.
```go
d, err := statsd.New("")
// Do some stuff
err = d.Close()
```
The app does this frequently enough that we discovered a leaked ticker. The DataDog continuous profiler helped zero in on the problem by hinting that the app was spending an increasing number of CPU cycles on `runtime.CheckTimers` and `runtime.netpoll`/`runtime.epollwait`. For a one-liner change, the effect is pretty outsized! You can spot the difference:
| ![Screen Shot 2022-11-24 at 1 31 20 PM](https://user-images.githubusercontent.com/11906832/203844815-254ef4b9-1d79-4041-8c4a-1d65a3e84a19.png) …
=> Bug fix: Call ticker.Stop() when aggregator is stopped

README.md, statsd/statsd.go, statsd/statsd_test.go
To keep parity with `ddtrace` (the Datadog Python APM Client), I've added support for `DD_DOGSTATSD_URL` that behaves as described in `ddtrace` docs [here](https://ddtrace.readthedocs.io/en/stable/configuration.html#DD_DOGSTATSD_URL).
> The URL to use to connect the Datadog agent for Dogstatsd metrics. The url can start with `udp://` to connect using UDP or with `unix://` to use a Unix Domain Socket.
>
> Example for UDP url: `DD_DOGSTATSD_URL=udp://localhost:8125`
>
> Example for UDS: `DD_DOGSTATSD_URL=unix:///var/run/datadog/dsd.socket`
>
If you use `DD_DOGSTATSD_URL=udp://localhost` it will add the correct port (i.e. change it to `DD_DOGSTATSD_URL=udp://localhost:8125`).
=> Adding support for DD_DOGSTATSD_URL

statsd/container.go, statsd/container_linux.go, statsd/container_stub.go, statsd/container_test.go
The DSD golang library is already able to auto-detect the container ID of the running process by inspecting `/proc/self/cgroup`.
Unfortunately, this technique stopped working with cgroup v2 which comes with cgroup namespace.
If the running process runs in a non-host cgroup namespace, its visible `/proc/self/cgroup` will not contain the container ID.
This PR implements an alternative way of finding the container ID in `/proc/self/mountinfo`.
If we’re using cgroup V1, we can still use the `/proc/self/cgroup`-based logic.
If we’re in the host cgroup namespace, we can still use the `/proc/self/cgroup`-based logic.
Otherwise, let’s make a try with `/proc/self/mountinfo`.
This PR replicates in the DSD golang client library the logic that has been introduced in DataDog/datadog-agent#14045.
=> Try to detect the container ID from `/proc/self/mountinfo`

statsd/buffer.go, statsd/error_handler.go, statsd/options.go, statsd/sender.go, statsd/sender_test.go, statsd/statsd.go, statsd/statsd_test.go, statsd/telemetry.go
From the point of view of the applications metrics (and buffers) are currently silently dropped. It makes it hard to:
- Make issues observable to the application and user (in logs for example)
- Allow the application to adapt its traffic to what the agent can handle
This commit adds:
- A way to return an error when metrics are dropped early
- A way to define an error handler (like https://github.com/DataDog/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/StatsDClientErrorHandler.java#L9)
By default both of these are disabled (for performance reasons) but would offer better observability in drops, their reason and how to act (change settings, etc..)
This is going to be increasingly necessary as multi-tenant environment will require back-pressure and drops will need to …
=> Give more error handling options the the applications

CHANGELOG.md, README.md, statsd/aggregator.go, statsd/aggregator_test.go, statsd/buffer.go, statsd/buffer_test.go, statsd/buffered_metric_context.go, statsd/end_to_end_udp_test.go, statsd/metrics.go, statsd/metrics_test.go, statsd/options.go, statsd/statsd.go, statsd/test_helpers_test.go, statsd/worker.go
Sampling rates are an inefficient mechanism to sample distributions because it requires the user to dynamically compute the sampling rate in order to effictively limit the load induced by distributions.
This adds `WithMaxSamplesPerContext(int)` which will limit the number of samples we keep per contexts to a fixed number that will be high enough to stay statisically relevant.
The sampling is done using using an algorithm called Vitter’s R), which randomly selects values with linearly-decreasing probability. This is a commonly used algorithm in instrumentation libraries (such as codahale). (see http://www.cs.umd.edu/~samir/498/vitter.pdf)
Additionally this fixes the computation of the `rate` for buffered metrics, this is important because it is forwarded to the agent and passed down to the …
=> Add a way to limit the number of samples we keep for buffered metrics

statsd/buffered_metric_context.go
We need to take the lock only if the metric doesn't exist, this should remove a lot of extra contention.
=> aggregator: avoid extra-locking in bufferedMetric.sample()

statsd/buffered_metric_context.go, statsd/metrics.go, statsd/metrics_test.go, statsd/options.go
062e18cef60a416fb19f9203534c936198e79595 introduced a performance regression by trying to fix the computation of the actual sampling rate.
This commit takes some shortcuts to reduce lock contention while trying to keep the sampling rate correct.
=> buffered_metrics: reduce a bit lock contention

statsd/aggregator.go, statsd/aggregator_test.go, statsd/statsd_benchmark_test.go
Before:
`BenchmarkGetContextNoTags-10    	39929401	        29.70 ns/op	      16 B/op	       1 allocs/op`
After:
`BenchmarkGetContextNoTags-10    	419886585	         2.902 ns/op	       0 B/op	       0 allocs/op`
This might look not much, but this makes a lot of difference in term of allocation when a counter is called repeatedly inside a loop.
This also fixes the other benchmarks that I wanted to run to validate I didn't cause regression but where not able to run properly
We can see it in this profile (referencing line 182 explicitely):
Referencing https://github.com/DataDog/datadog-go/blob/master/statsd/aggregator.go#L182 as the main cause of allocation
From a simple call to Count:
`statsd.Count("rollout.done", 1, nil, 1.0)`
=> aggregator: don't allocate memory if we don't have tags

statsd/container_linux.go, statsd/container_stub.go, statsd/container_test.go
This Pull Request implements the support of Origin Detection when the container-id is unavailable from inside the application container only with cgroupv2.
It first retrieves the cgroup node path by parsing `proc/self/cgroup` which is formatted differently in cgroup v1 and v2. See https://man7.org/linux/man-pages/man7/cgroups.7.html.
The format is a list of `hierarchy-ID:controller-list:cgroup-path ` similar to:
```
0::<path>
1:name=systemd:... // only in cgroupv1
```
Once the path is retrieved, we retrieve the inode of `/sys/fs/cgroup + <path>` where `<path>` is the path retrieved previously.
Not that:
- We use `os.Stat` which follows symlinks. Thus, we assume that the path is not a symlink
- We ignore cases where the inode is less than 2.
1. Create a dummy app or use mine …
=> [CONTINT-3542] Send `in-<inode>` using the cgroup controller when container-id cannot be retrieved

statsd/options.go, statsd/statsd.go, statsd/telemetry.go, statsd/uds.go, statsd/uds_test.go, statsd/uds_windows.go
This is similar to https://github.com/DataDog/java-dogstatsd-client/pull/228
The idea is to protect the client from starved connections (due to listener bugs) and reinitialise the connection as needed.
=> uds: implement a connect timeout option

statsd/container_linux.go, statsd/container_test.go
We noticed e2e test failures on Amazon Linux ECS Optimized OS. It runs with cgroupv1. The `kind` nodes are using docker and the pods use containerd. All the pods are running containers in the same cgroup namespace but this ns is the one allocated to the docker nodes, not the host cgroup namespace. Thus, we don't verify that the cid is found in /proc/self/cgroup whereas we should. We also don't send the cgroup inode.
=> [CONTINT-3937] Fix origin detection when the cgroup namespace is shared but is not host cgroup ns

statsd/end_to_end_udp_test.go, statsd/options.go, statsd/statsd.go, statsd/statsd_test.go
We would like customers to be able to retrieve container tags even when `DD_ENTITY_ID` is set to false. The current behavior does not send the container-id if the entity id is set.
Note that the admission controller will set the container-id on Kubernetes.
For those who do not want container-tags, several alternatives are possible:
- Send the tag `dd.internal.card=none`
- Inject `DD_ORIGIN_DETECTION_ENABLED=false` to the application pod
See this doc for reference
=> [CONTINT-3864] Send both origin the container-id and the ENTITY_ID

statsd/statsd.go, statsd/statsd_test.go, statsd/telemetry.go
Today, statsd client that use DD_AGENT_HOST for their address
cannot be cloned:
// export DD_AGENT_HOST=localhost:8125
client, err := statsd.New("")
if err != nil {
log.Fatal(err)
}
cloned, err := statsd.CloneWithExtraOptions(client, /* ... */)
fmt.Println(err)  // can't clone client with no addrOption
This is because we resolve the address in createWriter,
but do not record the resolved address in the client.
func New(addr string, options ...Option) (*Client, error) {
// ...
... := createWriter(addr, /* ... */) // resolves addr internally
// ...
client.addrOption = addr  // addr is old, unresolved value
}
This commit fixes this issue by replacing the address
with the resolved value so that that's what we record on the client,
allowing it to be cloned.
Testing: Includes a regression test …
=> fix: Support cloning clients that use DD_AGENT_HOST

statsd/statsd_benchmark_test.go
Added `WithoutOriginDetection()` to `setupClient()` in `statsd_benckmark_test.go` to fix benches on Linux.
=> add `WithoutOriginDetection()` to `setupClient()` in benches
